// Inside vue.config.js
const PrerenderSPAPlugin = require('prerender-spa-plugin');  // Introducing plug-ins
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer;
const path = require('path');
module.exports = {
    publicPath:'/',

    pwa: {
            name: 'Conversion Today',
            themeColor: '#545454',
        //     msTileColor: '#000000',
        //     appleMobileWebAppCapable: 'yes',
        //     appleMobileWebAppStatusBarStyle: 'black',

        // manifestOptions: {
        //     start_url: './dist/'
        // },

        // manifestPath: './dist/manifest.json',
    },
    configureWebpack: () => {
      if (process.env.NODE_ENV !== 'production') return;
      return {
          plugins: [
              new PrerenderSPAPlugin({
                  // The path to generate the file can also be consistent with the webpakc package.
                  // This directory can only have one level, if the directory level is higher than one level, there will be no error prompt when it is generated, and it will only stick when it is pre-rendered.
                  staticDir: path.join(__dirname,'dist'),
                  // If you have parameters for your own routing file, such as about, you need to write / about/param1.
                    routes: ["/","/image/jpg","/image/jpg/jpg","/image/jpg/jpeg","/image/jpg/png","/image/jpg/tiff",
                  "/image/jpg/webp","/image/jpg/gif","/image/jpg/bmp","/image/jpg/svg",
                  "/image/jpg/psd","/image/jpg/ai","/image/jpg/eps","/image/jpg/svgz",
                  "/image/jpg/dcx","/image/jpg/dds","/image/jpg/dpx","/image/jpg/exr",
                  "/image/jpg/fits","/image/jpg/jpc","/image/jpg/jpe","/image/jpg/jps",
                  "/image/jpg/jpm","/image/jpg/jfif","/image/jpg/jng","/image/jpg/j2c",
                  "/image/jpg/j2k","/image/jpg/miff","/image/jpg/mng","/image/jpg/palm",
                  "/image/jpg/pam","/image/jpg/pbm","/image/jpg/pcd","/image/jpg/pcds",
                  "/image/jpg/pcl","/image/jpg/pcx","/image/jpg/pfa","/image/jpg/pgm",
                  "/image/jpg/psb","/image/jpg/ptif","/image/jpg/p7","/image/jpg/ras",
                  "/image/jpg/sgi","/image/jpg/sun","/image/jpg/tga","/image/jpg/vda",
                  "/image/jpg/vicar","/image/jpg/viff","/image/jpg/vips","/image/jpg/xbm",
                  "/image/jpg/xpm","/image/jpg/xv","/image/jpeg","/image/jpeg/jpg","/image/jpeg/jpeg",
                  "/image/jpeg/png","/image/jpeg/tiff","/image/jpeg/webp","/image/jpeg/gif",
                  "/image/jpeg/bmp","/image/jpeg/svg","/image/jpeg/psd","/image/jpeg/ai",
                  "/image/jpeg/eps","/image/jpeg/svgz","/image/jpeg/dcx","/image/jpeg/dds",
                  "/image/jpeg/dpx","/image/jpeg/exr","/image/jpeg/fits","/image/jpeg/jpc",
                  "/image/jpeg/jpe","/image/jpeg/jps","/image/jpeg/jpm","/image/jpeg/jfif",
                  "/image/jpeg/jng","/image/jpeg/j2c","/image/jpeg/j2k","/image/jpeg/miff",
                  "/image/jpeg/mng","/image/jpeg/palm","/image/jpeg/pam","/image/jpeg/pbm",
                  "/image/jpeg/pcd","/image/jpeg/pcds","/image/jpeg/pcl","/image/jpeg/pcx",
                  "/image/jpeg/pfa","/image/jpeg/pgm","/image/jpeg/psb","/image/jpeg/ptif",
                  "/image/jpeg/p7","/image/jpeg/ras","/image/jpeg/sgi","/image/jpeg/sun",
                  "/image/jpeg/tga","/image/jpeg/vda","/image/jpeg/vicar","/image/jpeg/viff",
                  "/image/jpeg/vips","/image/jpeg/xbm","/image/jpeg/xpm","/image/jpeg/xv",
                  "/image/png","/image/png/jpg","/image/png/jpeg","/image/png/png","/image/png/tiff",
                  "/image/png/webp","/image/png/gif","/image/png/bmp","/image/png/svg","/image/png/psd",
                  "/image/png/ai","/image/png/eps","/image/png/svgz","/image/png/dcx","/image/png/dds",
                  "/image/png/dpx","/image/png/exr","/image/png/fits","/image/png/jpc","/image/png/jpe",
                  "/image/png/jps","/image/png/jpm","/image/png/jfif","/image/png/jng","/image/png/j2c",
                  "/image/png/j2k","/image/png/miff","/image/png/mng","/image/png/palm","/image/png/pam",
                  "/image/png/pbm","/image/png/pcd","/image/png/pcds","/image/png/pcl","/image/png/pcx",
                  "/image/png/pfa","/image/png/pgm","/image/png/psb","/image/png/ptif","/image/png/p7",
                  "/image/png/ras","/image/png/sgi","/image/png/sun","/image/png/tga","/image/png/vda",
                  "/image/png/vicar","/image/png/viff","/image/png/vips","/image/png/xbm","/image/png/xpm",
                  "/image/png/xv","/image/tiff","/image/tiff/jpg","/image/tiff/jpeg","/image/tiff/png",
                  "/image/tiff/tiff","/image/tiff/webp","/image/tiff/gif","/image/tiff/bmp",
                  "/image/tiff/svg","/image/tiff/psd","/image/tiff/ai","/image/tiff/eps",
                  "/image/tiff/svgz","/image/tiff/dcx","/image/tiff/dds","/image/tiff/dpx",
                  "/image/tiff/exr","/image/tiff/fits","/image/tiff/jpc","/image/tiff/jpe",
                  "/image/tiff/jps","/image/tiff/jpm","/image/tiff/jfif","/image/tiff/jng",
                  "/image/tiff/j2c","/image/tiff/j2k","/image/tiff/miff","/image/tiff/mng",
                  "/image/tiff/palm","/image/tiff/pam","/image/tiff/pbm","/image/tiff/pcd",
                  "/image/tiff/pcds","/image/tiff/pcl","/image/tiff/pcx","/image/tiff/pfa",
                  "/image/tiff/pgm","/image/tiff/psb","/image/tiff/ptif","/image/tiff/p7",
                  "/image/tiff/ras","/image/tiff/sgi","/image/tiff/sun","/image/tiff/tga",
                  "/image/tiff/vda","/image/tiff/vicar","/image/tiff/viff","/image/tiff/vips",
                  "/image/tiff/xbm","/image/tiff/xpm","/image/tiff/xv","/image/webp","/image/webp/jpg",
                  "/image/webp/jpeg","/image/webp/png","/image/webp/tiff","/image/webp/webp",
                  "/image/webp/gif","/image/webp/bmp","/image/webp/svg","/image/webp/psd",
                  "/image/webp/ai","/image/webp/eps","/image/webp/svgz","/image/webp/dcx",
                  "/image/webp/dds","/image/webp/dpx","/image/webp/exr","/image/webp/fits",
                  "/image/webp/jpc","/image/webp/jpe","/image/webp/jps","/image/webp/jpm",
                  "/image/webp/jfif","/image/webp/jng","/image/webp/j2c","/image/webp/j2k",
                  "/image/webp/miff","/image/webp/mng","/image/webp/palm","/image/webp/pam",
                  "/image/webp/pbm","/image/webp/pcd","/image/webp/pcds","/image/webp/pcl",
                  "/image/webp/pcx","/image/webp/pfa","/image/webp/pgm","/image/webp/psb",
                  "/image/webp/ptif","/image/webp/p7","/image/webp/ras","/image/webp/sgi",
                  "/image/webp/sun","/image/webp/tga","/image/webp/vda","/image/webp/vicar",
                  "/image/webp/viff","/image/webp/vips","/image/webp/xbm","/image/webp/xpm",
                  "/image/webp/xv","/image/gif","/image/gif/jpg","/image/gif/jpeg","/image/gif/png",
                  "/image/gif/tiff","/image/gif/webp","/image/gif/gif","/image/gif/bmp","/image/gif/svg",
                  "/image/gif/psd","/image/gif/ai","/image/gif/eps","/image/gif/svgz","/image/gif/dcx",
                  "/image/gif/dds","/image/gif/dpx","/image/gif/exr","/image/gif/fits","/image/gif/jpc",
                  "/image/gif/jpe","/image/gif/jps","/image/gif/jpm","/image/gif/jfif","/image/gif/jng",
                  "/image/gif/j2c","/image/gif/j2k","/image/gif/miff","/image/gif/mng","/image/gif/palm",
                  "/image/gif/pam","/image/gif/pbm","/image/gif/pcd","/image/gif/pcds","/image/gif/pcl",
                  "/image/gif/pcx","/image/gif/pfa","/image/gif/pgm","/image/gif/psb","/image/gif/ptif",
                  "/image/gif/p7","/image/gif/ras","/image/gif/sgi","/image/gif/sun","/image/gif/tga",
                  "/image/gif/vda","/image/gif/vicar","/image/gif/viff","/image/gif/vips","/image/gif/xbm",
                  "/image/gif/xpm","/image/gif/xv","/image/bmp","/image/bmp/jpg","/image/bmp/jpeg","/image/bmp/png",
                  "/image/bmp/tiff","/image/bmp/webp","/image/bmp/gif","/image/bmp/bmp","/image/bmp/svg","/image/bmp/psd",
                  "/image/bmp/ai","/image/bmp/eps","/image/bmp/svgz","/image/bmp/dcx","/image/bmp/dds","/image/bmp/dpx",
                  "/image/bmp/exr","/image/bmp/fits","/image/bmp/jpc","/image/bmp/jpe","/image/bmp/jps","/image/bmp/jpm",
                  "/image/bmp/jfif","/image/bmp/jng","/image/bmp/j2c","/image/bmp/j2k","/image/bmp/miff","/image/bmp/mng",
                  "/image/bmp/palm","/image/bmp/pam","/image/bmp/pbm","/image/bmp/pcd","/image/bmp/pcds","/image/bmp/pcl",
                  "/image/bmp/pcx","/image/bmp/pfa","/image/bmp/pgm","/image/bmp/psb","/image/bmp/ptif","/image/bmp/p7",
                  "/image/bmp/ras","/image/bmp/sgi","/image/bmp/sun","/image/bmp/tga","/image/bmp/vda","/image/bmp/vicar",
                  "/image/bmp/viff","/image/bmp/vips","/image/bmp/xbm","/image/bmp/xpm","/image/bmp/xv","/image/psd",
                  "/image/psd/jpg","/image/psd/jpeg","/image/psd/png","/image/psd/tiff","/image/psd/webp","/image/psd/gif",
                  "/image/psd/bmp","/image/psd/svg","/image/psd/psd","/image/psd/ai","/image/psd/eps","/image/psd/svgz",
                  "/image/psd/dcx","/image/psd/dds","/image/psd/dpx","/image/psd/exr","/image/psd/fits","/image/psd/jpc",
                  "/image/psd/jpe","/image/psd/jps","/image/psd/jpm","/image/psd/jfif","/image/psd/jng","/image/psd/j2c",
                  "/image/psd/j2k","/image/psd/miff","/image/psd/mng","/image/psd/palm","/image/psd/pam","/image/psd/pbm",
                  "/image/psd/pcd","/image/psd/pcds","/image/psd/pcl","/image/psd/pcx","/image/psd/pfa","/image/psd/pgm",
                  "/image/psd/psb", "/image/psd/ptif", "/image/psd/p7", "/image/psd/ras", "/image/psd/sgi", "/image/psd/sun", 
                  "/image/psd/tga", "/image/psd/vda", "/image/psd/vicar", "/image/psd/viff", "/image/psd/vips", 
                  "/image/psd/xbm", "/image/psd/xpm", "/image/psd/xv", "/image/dcx", "/image/dcx/jpg", "/image/dcx/jpeg", 
                  "/image/dcx/png", "/image/dcx/tiff", "/image/dcx/webp", "/image/dcx/gif", "/image/dcx/bmp", 
                  "/image/dcx/svg", "/image/dcx/psd", "/image/dcx/ai", "/image/dcx/eps", "/image/dcx/svgz", 
                  "/image/dcx/dcx", "/image/dcx/dds", "/image/dcx/dpx", "/image/dcx/exr", "/image/dcx/fits", 
                  "/image/dcx/jpc", "/image/dcx/jpe", "/image/dcx/jps", "/image/dcx/jpm", "/image/dcx/jfif", "/image/dcx/jng", 
                  "/image/dcx/j2c", "/image/dcx/j2k", "/image/dcx/miff", "/image/dcx/mng", "/image/dcx/palm", "/image/dcx/pam", 
                  "/image/dcx/pbm", "/image/dcx/pcd", "/image/dcx/pcds", "/image/dcx/pcl", "/image/dcx/pcx", "/image/dcx/pfa", 
                  "/image/dcx/pgm", "/image/dcx/psb", "/image/dcx/ptif", "/image/dcx/p7", "/image/dcx/ras", "/image/dcx/sgi", 
                  "/image/dcx/sun", "/image/dcx/tga", "/image/dcx/vda", "/image/dcx/vicar", "/image/dcx/viff", 
                  "/image/dcx/vips", "/image/dcx/xbm", "/image/dcx/xpm", "/image/dcx/xv", "/image/dds", "/image/dds/jpg", 
                  "/image/dds/jpeg", "/image/dds/png", "/image/dds/tiff", "/image/dds/webp", "/image/dds/gif", 
                  "/image/dds/bmp", "/image/dds/svg", "/image/dds/psd", "/image/dds/ai", "/image/dds/eps", "/image/dds/svgz", 
                  "/image/dds/dcx", "/image/dds/dds", "/image/dds/dpx", "/image/dds/exr", "/image/dds/fits", 
                  "/image/dds/jpc", "/image/dds/jpe", "/image/dds/jps", "/image/dds/jpm", "/image/dds/jfif", "/image/dds/jng", 
                  "/image/dds/j2c", "/image/dds/j2k", "/image/dds/miff", "/image/dds/mng", "/image/dds/palm", 
                  "/image/dds/pam", "/image/dds/pbm", "/image/dds/pcd", "/image/dds/pcds", "/image/dds/pcl", "/image/dds/pcx",
                   "/image/dds/pfa", "/image/dds/pgm", "/image/dds/psb", "/image/dds/ptif", "/image/dds/p7", 
                   "/image/dds/ras", "/image/dds/sgi", "/image/dds/sun", "/image/dds/tga", "/image/dds/vda", "/image/dds/vicar", 
                   "/image/dds/viff", "/image/dds/vips", "/image/dds/xbm", "/image/dds/xpm", "/image/dds/xv", "/image/dpx", 
                   "/image/dpx/jpg", "/image/dpx/jpeg", "/image/dpx/png", "/image/dpx/tiff", "/image/dpx/webp", 
                   "/image/dpx/gif", "/image/dpx/bmp", "/image/dpx/svg", "/image/dpx/psd", "/image/dpx/ai", "/image/dpx/eps", 
                   "/image/dpx/svgz", "/image/dpx/dcx", "/image/dpx/dds", "/image/dpx/dpx", "/image/dpx/exr", 
                   "/image/dpx/fits", "/image/dpx/jpc", "/image/dpx/jpe", "/image/dpx/jps", "/image/dpx/jpm", "/image/dpx/jfif", 
                   "/image/dpx/jng", "/image/dpx/j2c", "/image/dpx/j2k", "/image/dpx/miff", "/image/dpx/mng", 
                   "/image/dpx/palm", "/image/dpx/pam", "/image/dpx/pbm", "/image/dpx/pcd", "/image/dpx/pcds", "/image/dpx/pcl",
                    "/image/dpx/pcx", "/image/dpx/pfa", "/image/dpx/pgm", "/image/dpx/psb", "/image/dpx/ptif", 
                    "/image/dpx/p7", "/image/dpx/ras", "/image/dpx/sgi", "/image/dpx/sun", "/image/dpx/tga", "/image/dpx/vda", 
                    "/image/dpx/vicar", "/image/dpx/viff", "/image/dpx/vips", "/image/dpx/xbm", "/image/dpx/xpm",
                     "/image/dpx/xv", "/image/exr", "/image/exr/jpg", "/image/exr/jpeg", "/image/exr/png",
                      "/image/exr/tiff", "/image/exr/webp", "/image/exr/gif", "/image/exr/bmp", "/image/exr/svg",
                       "/image/exr/psd", "/image/exr/ai", "/image/exr/eps", "/image/exr/svgz", "/image/exr/dcx", 
                       "/image/exr/dds", "/image/exr/dpx", "/image/exr/exr", "/image/exr/fits", "/image/exr/jpc", 
                       "/image/exr/jpe", "/image/exr/jps", "/image/exr/jpm", "/image/exr/jfif", "/image/exr/jng", 
                       "/image/exr/j2c", "/image/exr/j2k", "/image/exr/miff", "/image/exr/mng", "/image/exr/palm",
                        "/image/exr/pam", "/image/exr/pbm", "/image/exr/pcd", "/image/exr/pcds", "/image/exr/pcl",
                         "/image/exr/pcx", "/image/exr/pfa", "/image/exr/pgm", "/image/exr/psb", "/image/exr/ptif",
                          "/image/exr/p7", "/image/exr/ras", "/image/exr/sgi", "/image/exr/sun", "/image/exr/tga", 
                          "/image/exr/vda", "/image/exr/vicar", "/image/exr/viff", "/image/exr/vips", "/image/exr/xbm",
                           "/image/exr/xpm", "/image/exr/xv", "/image/fits", "/image/fits/jpg", "/image/fits/jpeg", 
                           "/image/fits/png", "/image/fits/tiff", "/image/fits/webp", "/image/fits/gif", "/image/fits/bmp", 
                           "/image/fits/svg", "/image/fits/psd", "/image/fits/ai", "/image/fits/eps", "/image/fits/svgz",
                            "/image/fits/dcx", "/image/fits/dds", "/image/fits/dpx", "/image/fits/exr", "/image/fits/fits",
                             "/image/fits/jpc", "/image/fits/jpe", "/image/fits/jps", "/image/fits/jpm", "/image/fits/jfif", 
                             "/image/fits/jng", "/image/fits/j2c", "/image/fits/j2k", "/image/fits/miff", "/image/fits/mng",
                              "/image/fits/palm", "/image/fits/pam", "/image/fits/pbm", "/image/fits/pcd", "/image/fits/pcds", 
                              "/image/fits/pcl", "/image/fits/pcx", "/image/fits/pfa", "/image/fits/pgm", "/image/fits/psb", 
                              "/image/fits/ptif", "/image/fits/p7", "/image/fits/ras", "/image/fits/sgi", "/image/fits/sun",
                               "/image/fits/tga", "/image/fits/vda", "/image/fits/vicar", "/image/fits/viff", 
                               "/image/fits/vips", "/image/fits/xbm", "/image/fits/xpm", "/image/fits/xv", "/image/jpc",
                                "/image/jpc/jpg", "/image/jpc/jpeg", "/image/jpc/png", "/image/jpc/tiff", "/image/jpc/webp",
                                 "/image/jpc/gif", "/image/jpc/bmp", "/image/jpc/svg", "/image/jpc/psd", "/image/jpc/ai",
                                  "/image/jpc/eps", "/image/jpc/svgz", "/image/jpc/dcx", "/image/jpc/dds", "/image/jpc/dpx",
                                   "/image/jpc/exr", "/image/jpc/fits", "/image/jpc/jpc", "/image/jpc/jpe", "/image/jpc/jps", 
                                   "/image/jpc/jpm", "/image/jpc/jfif", "/image/jpc/jng", "/image/jpc/j2c", "/image/jpc/j2k", 
                                   "/image/jpc/miff", "/image/jpc/mng", "/image/jpc/palm", "/image/jpc/pam", "/image/jpc/pbm",
                                    "/image/jpc/pcd", "/image/jpc/pcds", "/image/jpc/pcl", "/image/jpc/pcx", "/image/jpc/pfa", 
                                    "/image/jpc/pgm", "/image/jpc/psb", "/image/jpc/ptif", "/image/jpc/p7", "/image/jpc/ras", 
                                    "/image/jpc/sgi", "/image/jpc/sun", "/image/jpc/tga", "/image/jpc/vda", "/image/jpc/vicar",
                   "/image/jpc/viff", "/image/jpc/vips", "/image/jpc/xbm", "/image/jpc/xpm", "/image/jpc/xv", "/image/jpe", 
                   "/image/jpe/jpg", "/image/jpe/jpeg", "/image/jpe/png", "/image/jpe/tiff", "/image/jpe/webp", 
                   "/image/jpe/gif", "/image/jpe/bmp", "/image/jpe/svg", "/image/jpe/psd", "/image/jpe/ai", "/image/jpe/eps",
                    "/image/jpe/svgz", "/image/jpe/dcx", "/image/jpe/dds", "/image/jpe/dpx", "/image/jpe/exr", "/image/jpe/fits", 
                    "/image/jpe/jpc", "/image/jpe/jpe", "/image/jpe/jps", "/image/jpe/jpm", "/image/jpe/jfif", 
                    "/image/jpe/jng", "/image/jpe/j2c", "/image/jpe/j2k", "/image/jpe/miff", "/image/jpe/mng", 
                    "/image/jpe/palm", "/image/jpe/pam", "/image/jpe/pbm", "/image/jpe/pcd", "/image/jpe/pcds", 
                    "/image/jpe/pcl", "/image/jpe/pcx", "/image/jpe/pfa", "/image/jpe/pgm", "/image/jpe/psb", 
                    "/image/jpe/ptif", "/image/jpe/p7", "/image/jpe/ras", "/image/jpe/sgi", "/image/jpe/sun", 
                    "/image/jpe/tga", "/image/jpe/vda", "/image/jpe/vicar", "/image/jpe/viff", "/image/jpe/vips", 
                    "/image/jpe/xbm", "/image/jpe/xpm", "/image/jpe/xv", "/image/jps", "/image/jps/jpg", "/image/jps/jpeg", 
                    "/image/jps/png", "/image/jps/tiff", "/image/jps/webp", "/image/jps/gif", "/image/jps/bmp", 
                    "/image/jps/svg", "/image/jps/psd", "/image/jps/ai", "/image/jps/eps", "/image/jps/svgz", 
                    "/image/jps/dcx", "/image/jps/dds", "/image/jps/dpx", "/image/jps/exr", "/image/jps/fits", 
                    "/image/jps/jpc", "/image/jps/jpe", "/image/jps/jps", "/image/jps/jpm", "/image/jps/jfif", 
                    "/image/jps/jng", "/image/jps/j2c", "/image/jps/j2k", "/image/jps/miff", "/image/jps/mng",
                     "/image/jps/palm", "/image/jps/pam", "/image/jps/pbm", "/image/jps/pcd", "/image/jps/pcds", 
                     "/image/jps/pcl", "/image/jps/pcx", "/image/jps/pfa", "/image/jps/pgm", "/image/jps/psb", 
                     "/image/jps/ptif", "/image/jps/p7", "/image/jps/ras", "/image/jps/sgi", "/image/jps/sun", 
                     "/image/jps/tga", "/image/jps/vda", "/image/jps/vicar", "/image/jps/viff", "/image/jps/vips", 
                     "/image/jps/xbm", "/image/jps/xpm", "/image/jps/xv", "/image/jpm", "/image/jpm/jpg", "/image/jpm/jpeg", 
                     "/image/jpm/png", "/image/jpm/tiff", "/image/jpm/webp", "/image/jpm/gif", "/image/jpm/bmp", 
                     "/image/jpm/svg", "/image/jpm/psd", "/image/jpm/ai", "/image/jpm/eps", "/image/jpm/svgz", 
                     "/image/jpm/dcx", "/image/jpm/dds", "/image/jpm/dpx", "/image/jpm/exr", "/image/jpm/fits", 
                     "/image/jpm/jpc", "/image/jpm/jpe", "/image/jpm/jps", "/image/jpm/jpm", "/image/jpm/jfif", 
                     "/image/jpm/jng", "/image/jpm/j2c", "/image/jpm/j2k", "/image/jpm/miff", "/image/jpm/mng", 
                     "/image/jpm/palm", "/image/jpm/pam", "/image/jpm/pbm", "/image/jpm/pcd", "/image/jpm/pcds", 
                     "/image/jpm/pcl", "/image/jpm/pcx", "/image/jpm/pfa", "/image/jpm/pgm", "/image/jpm/psb", 
                     "/image/jpm/ptif", "/image/jpm/p7", "/image/jpm/ras", "/image/jpm/sgi", "/image/jpm/sun", 
                     "/image/jpm/tga", "/image/jpm/vda", "/image/jpm/vicar", "/image/jpm/viff", "/image/jpm/vips", 
                     "/image/jpm/xbm", "/image/jpm/xpm", "/image/jpm/xv", "/image/jfif", "/image/jfif/jpg", "/image/jfif/jpeg", 
                     "/image/jfif/png", "/image/jfif/tiff", "/image/jfif/webp", "/image/jfif/gif", "/image/jfif/bmp", 
                     "/image/jfif/svg", "/image/jfif/psd", "/image/jfif/ai", "/image/jfif/eps", "/image/jfif/svgz", 
                     "/image/jfif/dcx", "/image/jfif/dds", "/image/jfif/dpx", "/image/jfif/exr", "/image/jfif/fits", 
                     "/image/jfif/jpc", "/image/jfif/jpe", "/image/jfif/jps", "/image/jfif/jpm", "/image/jfif/jfif", 
                     "/image/jfif/jng", "/image/jfif/j2c", "/image/jfif/j2k", "/image/jfif/miff", "/image/jfif/mng", 
                     "/image/jfif/palm", "/image/jfif/pam", "/image/jfif/pbm", "/image/jfif/pcd", "/image/jfif/pcds", 
                     "/image/jfif/pcl", "/image/jfif/pcx", "/image/jfif/pfa", "/image/jfif/pgm", "/image/jfif/psb", 
                     "/image/jfif/ptif", "/image/jfif/p7", "/image/jfif/ras", "/image/jfif/sgi", "/image/jfif/sun", 
                     "/image/jfif/tga", "/image/jfif/vda", "/image/jfif/vicar", "/image/jfif/viff", "/image/jfif/vips", 
                     "/image/jfif/xbm", "/image/jfif/xpm", "/image/jfif/xv", "/image/jng", "/image/jng/jpg", 
                     "/image/jng/jpeg", "/image/jng/png", "/image/jng/tiff", "/image/jng/webp", "/image/jng/gif", 
                     "/image/jng/bmp", "/image/jng/svg", "/image/jng/psd", "/image/jng/ai", "/image/jng/eps", 
                     "/image/jng/svgz", "/image/jng/dcx", "/image/jng/dds", "/image/jng/dpx", "/image/jng/exr", 
                     "/image/jng/fits", "/image/jng/jpc", "/image/jng/jpe", "/image/jng/jps", "/image/jng/jpm", 
                     "/image/jng/jfif", "/image/jng/jng", "/image/jng/j2c", "/image/jng/j2k", "/image/jng/miff", 
                     "/image/jng/mng", "/image/jng/palm", "/image/jng/pam", "/image/jng/pbm", "/image/jng/pcd", 
                     "/image/jng/pcds", "/image/jng/pcl", "/image/jng/pcx", "/image/jng/pfa", "/image/jng/pgm", 
                     "/image/jng/psb", "/image/jng/ptif", "/image/jng/p7", "/image/jng/ras", "/image/jng/sgi", 
                     "/image/jng/sun", "/image/jng/tga", "/image/jng/vda", "/image/jng/vicar", "/image/jng/viff", 
                     "/image/jng/vips", "/image/jng/xbm", "/image/jng/xpm", "/image/jng/xv", "/image/j2c", "/image/j2c/jpg", 
                     "/image/j2c/jpeg", "/image/j2c/png", "/image/j2c/tiff", "/image/j2c/webp", "/image/j2c/gif", 
                     "/image/j2c/bmp", "/image/j2c/svg", "/image/j2c/psd", "/image/j2c/ai", "/image/j2c/eps", 
                     "/image/j2c/svgz", "/image/j2c/dcx", "/image/j2c/dds", "/image/j2c/dpx", "/image/j2c/exr", 
                     "/image/j2c/fits", "/image/j2c/jpc", "/image/j2c/jpe", "/image/j2c/jps", "/image/j2c/jpm", 
                     "/image/j2c/jfif", "/image/j2c/jng", "/image/j2c/j2c", "/image/j2c/j2k", "/image/j2c/miff", 
                     "/image/j2c/mng", "/image/j2c/palm", "/image/j2c/pam", "/image/j2c/pbm", "/image/j2c/pcd", 
                     "/image/j2c/pcds", "/image/j2c/pcl", "/image/j2c/pcx", "/image/j2c/pfa", "/image/j2c/pgm", 
                     "/image/j2c/psb", "/image/j2c/ptif", "/image/j2c/p7", "/image/j2c/ras", "/image/j2c/sgi", 
                     "/image/j2c/sun", "/image/j2c/tga", "/image/j2c/vda", "/image/j2c/vicar", "/image/j2c/viff",
                      "/image/j2c/vips", "/image/j2c/xbm", "/image/j2c/xpm", "/image/j2c/xv", "/image/j2k", 
                      "/image/j2k/jpg", "/image/j2k/jpeg", "/image/j2k/png", "/image/j2k/tiff", "/image/j2k/webp",
                    "/image/j2k/gif", "/image/j2k/bmp", "/image/j2k/svg", "/image/j2k/psd", "/image/j2k/ai", "/image/j2k/eps", 
                    "/image/j2k/svgz", "/image/j2k/dcx", "/image/j2k/dds", "/image/j2k/dpx", "/image/j2k/exr", "/image/j2k/fits", 
                    "/image/j2k/jpc", "/image/j2k/jpe", "/image/j2k/jps", "/image/j2k/jpm", "/image/j2k/jfif", "/image/j2k/jng", 
                    "/image/j2k/j2c", "/image/j2k/j2k", "/image/j2k/miff", "/image/j2k/mng", "/image/j2k/palm", 
                    "/image/j2k/pam", "/image/j2k/pbm", "/image/j2k/pcd", "/image/j2k/pcds", "/image/j2k/pcl", 
                    "/image/j2k/pcx", "/image/j2k/pfa", "/image/j2k/pgm", "/image/j2k/psb", "/image/j2k/ptif", 
                    "/image/j2k/p7", "/image/j2k/ras", "/image/j2k/sgi", "/image/j2k/sun", "/image/j2k/tga", 
                    "/image/j2k/vda", "/image/j2k/vicar", "/image/j2k/viff", "/image/j2k/vips", "/image/j2k/xbm", 
                    "/image/j2k/xpm", "/image/j2k/xv", "/image/miff", "/image/miff/jpg", "/image/miff/jpeg", 
                    "/image/miff/png", "/image/miff/tiff", "/image/miff/webp", "/image/miff/gif", "/image/miff/bmp", 
                    "/image/miff/svg", "/image/miff/psd", "/image/miff/ai", "/image/miff/eps", "/image/miff/svgz",
                     "/image/miff/dcx", "/image/miff/dds", "/image/miff/dpx", "/image/miff/exr", "/image/miff/fits",
                      "/image/miff/jpc", "/image/miff/jpe", "/image/miff/jps", "/image/miff/jpm", "/image/miff/jfif",
                       "/image/miff/jng", "/image/miff/j2c", "/image/miff/j2k", "/image/miff/miff", "/image/miff/mng",
                        "/image/miff/palm", "/image/miff/pam", "/image/miff/pbm", "/image/miff/pcd", "/image/miff/pcds",
                         "/image/miff/pcl", "/image/miff/pcx", "/image/miff/pfa", "/image/miff/pgm", "/image/miff/psb",
                          "/image/miff/ptif", "/image/miff/p7", "/image/miff/ras", "/image/miff/sgi", "/image/miff/sun",
                           "/image/miff/tga", "/image/miff/vda", "/image/miff/vicar", "/image/miff/viff", "/image/miff/vips", 
                "/image/miff/xbm", "/image/miff/xpm", "/image/miff/xv", "/image/mng", "/image/mng/jpg", "/image/mng/jpeg", 
                "/image/mng/png", "/image/mng/tiff", "/image/mng/webp", "/image/mng/gif", "/image/mng/bmp", "/image/mng/svg", 
                "/image/mng/psd", "/image/mng/ai", "/image/mng/eps", "/image/mng/svgz", "/image/mng/dcx", "/image/mng/dds", 
                "/image/mng/dpx", "/image/mng/exr", "/image/mng/fits", "/image/mng/jpc", "/image/mng/jpe", "/image/mng/jps", 
                "/image/mng/jpm", "/image/mng/jfif", "/image/mng/jng", "/image/mng/j2c", "/image/mng/j2k", "/image/mng/miff", 
                "/image/mng/mng", "/image/mng/palm", "/image/mng/pam", "/image/mng/pbm", "/image/mng/pcd", "/image/mng/pcds", 
                "/image/mng/pcl", "/image/mng/pcx", "/image/mng/pfa", "/image/mng/pgm", "/image/mng/psb", "/image/mng/ptif", 
                "/image/mng/p7", "/image/mng/ras", "/image/mng/sgi", "/image/mng/sun", "/image/mng/tga", "/image/mng/vda", 
                "/image/mng/vicar", "/image/mng/viff", "/image/mng/vips", "/image/mng/xbm", "/image/mng/xpm", "/image/mng/xv", 
                "/image/pam", "/image/pam/jpg", "/image/pam/jpeg", "/image/pam/png", "/image/pam/tiff", "/image/pam/webp", 
                "/image/pam/gif", "/image/pam/bmp", "/image/pam/svg", "/image/pam/psd", "/image/pam/ai", "/image/pam/eps", 
                "/image/pam/svgz", "/image/pam/dcx", "/image/pam/dds", "/image/pam/dpx", "/image/pam/exr", "/image/pam/fits", 
                "/image/pam/jpc", "/image/pam/jpe", "/image/pam/jps", "/image/pam/jpm", "/image/pam/jfif", "/image/pam/jng", 
                "/image/pam/j2c", "/image/pam/j2k", "/image/pam/miff", "/image/pam/mng", "/image/pam/palm", "/image/pam/pam", 
                "/image/pam/pbm", "/image/pam/pcd", "/image/pam/pcds", "/image/pam/pcl", "/image/pam/pcx", "/image/pam/pfa", 
                "/image/pam/pgm", "/image/pam/psb", "/image/pam/ptif", "/image/pam/p7", "/image/pam/ras", "/image/pam/sgi", 
                "/image/pam/sun", "/image/pam/tga", "/image/pam/vda", "/image/pam/vicar", "/image/pam/viff", 
                "/image/pam/vips", "/image/pam/xbm", "/image/pam/xpm", "/image/pam/xv", "/image/pbm", "/image/pbm/jpg", 
                "/image/pbm/jpeg", "/image/pbm/png", "/image/pbm/tiff", "/image/pbm/webp", "/image/pbm/gif", 
                "/image/pbm/bmp", "/image/pbm/svg", "/image/pbm/psd", "/image/pbm/ai", "/image/pbm/eps", 
                "/image/pbm/svgz", "/image/pbm/dcx", "/image/pbm/dds", "/image/pbm/dpx", "/image/pbm/exr", 
                "/image/pbm/fits", "/image/pbm/jpc", "/image/pbm/jpe", "/image/pbm/jps", "/image/pbm/jpm", 
                "/image/pbm/jfif", "/image/pbm/jng", "/image/pbm/j2c", "/image/pbm/j2k", "/image/pbm/miff", 
                "/image/pbm/mng", "/image/pbm/palm", "/image/pbm/pam", "/image/pbm/pbm", "/image/pbm/pcd", 
                "/image/pbm/pcds", "/image/pbm/pcl", "/image/pbm/pcx", "/image/pbm/pfa", "/image/pbm/pgm", 
                "/image/pbm/psb", "/image/pbm/ptif", "/image/pbm/p7", "/image/pbm/ras", "/image/pbm/sgi", 
                "/image/pbm/sun", "/image/pbm/tga", "/image/pbm/vda", "/image/pbm/vicar", "/image/pbm/viff", 
                "/image/pbm/vips", "/image/pbm/xbm", "/image/pbm/xpm", "/image/pbm/xv", "/image/pcd", 
                "/image/pcd/jpg", "/image/pcd/jpeg", "/image/pcd/png", "/image/pcd/tiff", "/image/pcd/webp", 
                "/image/pcd/gif", "/image/pcd/bmp", "/image/pcd/svg", "/image/pcd/psd", "/image/pcd/ai", "/image/pcd/eps", 
                "/image/pcd/svgz", "/image/pcd/dcx", "/image/pcd/dds", "/image/pcd/dpx", "/image/pcd/exr", "/image/pcd/fits", 
                "/image/pcd/jpc", "/image/pcd/jpe", "/image/pcd/jps", "/image/pcd/jpm", "/image/pcd/jfif", "/image/pcd/jng", 
                "/image/pcd/j2c", "/image/pcd/j2k", "/image/pcd/miff", "/image/pcd/mng", "/image/pcd/palm", "/image/pcd/pam", 
                "/image/pcd/pbm", "/image/pcd/pcd", "/image/pcd/pcds", "/image/pcd/pcl", "/image/pcd/pcx", "/image/pcd/pfa", 
                "/image/pcd/pgm", "/image/pcd/psb", "/image/pcd/ptif", "/image/pcd/p7", "/image/pcd/ras", "/image/pcd/sgi", 
                "/image/pcd/sun", "/image/pcd/tga", "/image/pcd/vda", "/image/pcd/vicar", "/image/pcd/viff", "/image/pcd/vips", 
                "/image/pcd/xbm", "/image/pcd/xpm", "/image/pcd/xv", "/image/pcds", "/image/pcds/jpg", "/image/pcds/jpeg", 
                "/image/pcds/png", "/image/pcds/tiff", "/image/pcds/webp", "/image/pcds/gif", "/image/pcds/bmp", 
                "/image/pcds/svg", "/image/pcds/psd", "/image/pcds/ai", "/image/pcds/eps", "/image/pcds/svgz", 
                "/image/pcds/dcx", "/image/pcds/dds", "/image/pcds/dpx", "/image/pcds/exr", "/image/pcds/fits", 
                "/image/pcds/jpc", "/image/pcds/jpe", "/image/pcds/jps", "/image/pcds/jpm", "/image/pcds/jfif", 
                "/image/pcds/jng", "/image/pcds/j2c", "/image/pcds/j2k", "/image/pcds/miff", "/image/pcds/mng", 
                "/image/pcds/palm", "/image/pcds/pam", "/image/pcds/pbm", "/image/pcds/pcd", "/image/pcds/pcds", 
                "/image/pcds/pcl", "/image/pcds/pcx", "/image/pcds/pfa", "/image/pcds/pgm", "/image/pcds/psb", 
                "/image/pcds/ptif", "/image/pcds/p7", "/image/pcds/ras", "/image/pcds/sgi", "/image/pcds/sun", 
                "/image/pcds/tga", "/image/pcds/vda", "/image/pcds/vicar", "/image/pcds/viff", "/image/pcds/vips", 
                "/image/pcds/xbm", "/image/pcds/xpm", "/image/pcds/xv", "/image/pcl", "/image/pcl/jpg", "/image/pcl/jpeg", 
                "/image/pcl/png", "/image/pcl/tiff", "/image/pcl/webp", "/image/pcl/gif", "/image/pcl/bmp", "/image/pcl/svg", 
                "/image/pcl/psd", "/image/pcl/ai", "/image/pcl/eps", "/image/pcl/svgz", "/image/pcl/dcx", "/image/pcl/dds", 
                "/image/pcl/dpx", "/image/pcl/exr", "/image/pcl/fits", "/image/pcl/jpc", "/image/pcl/jpe", "/image/pcl/jps", 
                "/image/pcl/jpm", "/image/pcl/jfif", "/image/pcl/jng", "/image/pcl/j2c", "/image/pcl/j2k", "/image/pcl/miff", 
                "/image/pcl/mng", "/image/pcl/palm", "/image/pcl/pam", "/image/pcl/pbm", "/image/pcl/pcd", "/image/pcl/pcds", 
                "/image/pcl/pcl", "/image/pcl/pcx", "/image/pcl/pfa", "/image/pcl/pgm", "/image/pcl/psb", "/image/pcl/ptif", 
                "/image/pcl/p7", "/image/pcl/ras", "/image/pcl/sgi", "/image/pcl/sun", "/image/pcl/tga", "/image/pcl/vda", 
                "/image/pcl/vicar", "/image/pcl/viff", "/image/pcl/vips", "/image/pcl/xbm", "/image/pcl/xpm", "/image/pcl/xv", 
                "/image/pcx", "/image/pcx/jpg", "/image/pcx/jpeg", "/image/pcx/png", "/image/pcx/tiff", "/image/pcx/webp", 
                "/image/pcx/gif", "/image/pcx/bmp", "/image/pcx/svg", "/image/pcx/psd", "/image/pcx/ai", "/image/pcx/eps", 
                "/image/pcx/svgz", "/image/pcx/dcx", "/image/pcx/dds", "/image/pcx/dpx", "/image/pcx/exr", "/image/pcx/fits", 
                "/image/pcx/jpc", "/image/pcx/jpe", "/image/pcx/jps", "/image/pcx/jpm", "/image/pcx/jfif", "/image/pcx/jng", 
                "/image/pcx/j2c", "/image/pcx/j2k", "/image/pcx/miff", "/image/pcx/mng", "/image/pcx/palm", "/image/pcx/pam",
                "/image/pcx/pbm", "/image/pcx/pcd", "/image/pcx/pcds", "/image/pcx/pcl", "/image/pcx/pcx", "/image/pcx/pfa", 
                "/image/pcx/pgm", "/image/pcx/psb", "/image/pcx/ptif", "/image/pcx/p7", "/image/pcx/ras", "/image/pcx/sgi", 
                "/image/pcx/sun", "/image/pcx/tga", "/image/pcx/vda", "/image/pcx/vicar", "/image/pcx/viff", "/image/pcx/vips", 
                "/image/pcx/xbm", "/image/pcx/xpm", "/image/pcx/xv", "/image/pfa", "/image/pfa/jpg", "/image/pfa/jpeg", 
                "/image/pfa/png", "/image/pfa/tiff", "/image/pfa/webp", "/image/pfa/gif", "/image/pfa/bmp", "/image/pfa/svg", 
                "/image/pfa/psd", "/image/pfa/ai", "/image/pfa/eps", "/image/pfa/svgz", "/image/pfa/dcx", "/image/pfa/dds", 
                "/image/pfa/dpx", "/image/pfa/exr", "/image/pfa/fits", "/image/pfa/jpc", "/image/pfa/jpe", "/image/pfa/jps", 
                "/image/pfa/jpm", "/image/pfa/jfif", "/image/pfa/jng", "/image/pfa/j2c", "/image/pfa/j2k", "/image/pfa/miff", 
                "/image/pfa/mng", "/image/pfa/palm", "/image/pfa/pam", "/image/pfa/pbm", "/image/pfa/pcd", "/image/pfa/pcds", 
                "/image/pfa/pcl", "/image/pfa/pcx", "/image/pfa/pfa", "/image/pfa/pgm", "/image/pfa/psb", "/image/pfa/ptif", 
                "/image/pfa/p7", "/image/pfa/ras", "/image/pfa/sgi", "/image/pfa/sun", "/image/pfa/tga", "/image/pfa/vda", 
                "/image/pfa/vicar", "/image/pfa/viff", "/image/pfa/vips", "/image/pfa/xbm", "/image/pfa/xpm", "/image/pfa/xv", 
                "/image/pgm", "/image/pgm/jpg", "/image/pgm/jpeg", "/image/pgm/png", "/image/pgm/tiff", "/image/pgm/webp", 
                "/image/pgm/gif", "/image/pgm/bmp", "/image/pgm/svg", "/image/pgm/psd", "/image/pgm/ai", "/image/pgm/eps", 
                "/image/pgm/svgz", "/image/pgm/dcx", "/image/pgm/dds", "/image/pgm/dpx", "/image/pgm/exr", "/image/pgm/fits", 
                "/image/pgm/jpc", "/image/pgm/jpe", "/image/pgm/jps", "/image/pgm/jpm", "/image/pgm/jfif", "/image/pgm/jng", 
                "/image/pgm/j2c", "/image/pgm/j2k", "/image/pgm/miff", "/image/pgm/mng", "/image/pgm/palm", "/image/pgm/pam", 
                "/image/pgm/pbm", "/image/pgm/pcd", "/image/pgm/pcds", "/image/pgm/pcl", "/image/pgm/pcx", "/image/pgm/pfa", 
                "/image/pgm/pgm", "/image/pgm/psb", "/image/pgm/ptif", "/image/pgm/p7", "/image/pgm/ras", "/image/pgm/sgi", 
                "/image/pgm/sun", "/image/pgm/tga", "/image/pgm/vda", "/image/pgm/vicar", "/image/pgm/viff", "/image/pgm/vips", 
                "/image/pgm/xbm", "/image/pgm/xpm", "/image/pgm/xv", "/image/psb", "/image/psb/jpg", "/image/psb/jpeg", 
                "/image/psb/png", "/image/psb/tiff", "/image/psb/webp", "/image/psb/gif", "/image/psb/bmp", "/image/psb/svg", 
                "/image/psb/psd", "/image/psb/ai", "/image/psb/eps", "/image/psb/svgz", "/image/psb/dcx", "/image/psb/dds", 
                "/image/psb/dpx", "/image/psb/exr", "/image/psb/fits", "/image/psb/jpc", "/image/psb/jpe", "/image/psb/jps", 
                "/image/psb/jpm", "/image/psb/jfif", "/image/psb/jng", "/image/psb/j2c", "/image/psb/j2k", "/image/psb/miff", 
                "/image/psb/mng", "/image/psb/palm", "/image/psb/pam", "/image/psb/pbm", "/image/psb/pcd", "/image/psb/pcds", 
                "/image/psb/pcl", "/image/psb/pcx", "/image/psb/pfa", "/image/psb/pgm", "/image/psb/psb", "/image/psb/ptif", 
                "/image/psb/p7", "/image/psb/ras", "/image/psb/sgi", "/image/psb/sun", "/image/psb/tga", "/image/psb/vda", 
                "/image/psb/vicar", "/image/psb/viff", "/image/psb/vips", "/image/psb/xbm", "/image/psb/xpm", "/image/psb/xv", 
                "/image/ptif", "/image/ptif/jpg", "/image/ptif/jpeg", "/image/ptif/png", "/image/ptif/tiff", "/image/ptif/webp", 
                "/image/ptif/gif", "/image/ptif/bmp", "/image/ptif/svg", "/image/ptif/psd", "/image/ptif/ai", "/image/ptif/eps", 
                "/image/ptif/svgz", "/image/ptif/dcx", "/image/ptif/dds", "/image/ptif/dpx", "/image/ptif/exr", 
                "/image/ptif/fits", "/image/ptif/jpc", "/image/ptif/jpe", "/image/ptif/jps", "/image/ptif/jpm", 
                "/image/ptif/jfif", "/image/ptif/jng", "/image/ptif/j2c", "/image/ptif/j2k", "/image/ptif/miff", 
                "/image/ptif/mng", "/image/ptif/palm", "/image/ptif/pam", "/image/ptif/pbm", "/image/ptif/pcd", 
                "/image/ptif/pcds", "/image/ptif/pcl", "/image/ptif/pcx", "/image/ptif/pfa", "/image/ptif/pgm", 
                "/image/ptif/psb", "/image/ptif/ptif", "/image/ptif/p7", "/image/ptif/ras", "/image/ptif/sgi", 
                "/image/ptif/sun", "/image/ptif/tga", "/image/ptif/vda", "/image/ptif/vicar", "/image/ptif/viff", 
                "/image/ptif/vips", "/image/ptif/xbm", "/image/ptif/xpm", "/image/ptif/xv", "/image/p7", 
                "/image/p7/jpg", "/image/p7/jpeg", "/image/p7/png", "/image/p7/tiff", "/image/p7/webp", "/image/p7/gif", 
                "/image/p7/bmp", "/image/p7/svg", "/image/p7/psd", "/image/p7/ai", "/image/p7/eps", "/image/p7/svgz", 
                "/image/p7/dcx", "/image/p7/dds", "/image/p7/dpx", "/image/p7/exr", "/image/p7/fits", "/image/p7/jpc", 
                "/image/p7/jpe", "/image/p7/jps", "/image/p7/jpm", "/image/p7/jfif", "/image/p7/jng", "/image/p7/j2c", 
                "/image/p7/j2k", "/image/p7/miff", "/image/p7/mng", "/image/p7/palm", "/image/p7/pam", "/image/p7/pbm", 
                "/image/p7/pcd", "/image/p7/pcds", "/image/p7/pcl", "/image/p7/pcx", "/image/p7/pfa", "/image/p7/pgm", 
                "/image/p7/psb", "/image/p7/ptif", "/image/p7/p7", "/image/p7/ras", "/image/p7/sgi", "/image/p7/sun", 
                "/image/p7/tga", "/image/p7/vda", "/image/p7/vicar", "/image/p7/viff", "/image/p7/vips", "/image/p7/xbm", 
                "/image/p7/xpm", "/image/p7/xv", "/image/ras", "/image/ras/jpg", "/image/ras/jpeg", "/image/ras/png", 
                "/image/ras/tiff", "/image/ras/webp", "/image/ras/gif", "/image/ras/bmp", "/image/ras/svg", "/image/ras/psd", 
                "/image/ras/ai", "/image/ras/eps", "/image/ras/svgz", "/image/ras/dcx", "/image/ras/dds", "/image/ras/dpx", 
                "/image/ras/exr", "/image/ras/fits", "/image/ras/jpc", "/image/ras/jpe", "/image/ras/jps", "/image/ras/jpm", 
                "/image/ras/jfif", "/image/ras/jng", "/image/ras/j2c", "/image/ras/j2k", "/image/ras/miff", "/image/ras/mng", 
                "/image/ras/palm", "/image/ras/pam", "/image/ras/pbm", "/image/ras/pcd", "/image/ras/pcds", "/image/ras/pcl", 
                "/image/ras/pcx", "/image/ras/pfa", "/image/ras/pgm", "/image/ras/psb", "/image/ras/ptif", "/image/ras/p7", 
                "/image/ras/ras", "/image/ras/sgi", "/image/ras/sun", "/image/ras/tga", "/image/ras/vda", "/image/ras/vicar", 
                "/image/ras/viff", "/image/ras/vips", "/image/ras/xbm", "/image/ras/xpm", "/image/ras/xv", "/image/sgi", 
                "/image/sgi/jpg", "/image/sgi/jpeg", "/image/sgi/png", "/image/sgi/tiff", "/image/sgi/webp", "/image/sgi/gif", 
                "/image/sgi/bmp", "/image/sgi/svg", "/image/sgi/psd", "/image/sgi/ai", "/image/sgi/eps", "/image/sgi/svgz", 
                "/image/sgi/dcx", "/image/sgi/dds", "/image/sgi/dpx", "/image/sgi/exr", "/image/sgi/fits", "/image/sgi/jpc", 
                "/image/sgi/jpe", "/image/sgi/jps", "/image/sgi/jpm", "/image/sgi/jfif", "/image/sgi/jng", "/image/sgi/j2c", 
                "/image/sgi/j2k", "/image/sgi/miff", "/image/sgi/mng", "/image/sgi/palm", "/image/sgi/pam", "/image/sgi/pbm", 
                "/image/sgi/pcd", "/image/sgi/pcds", "/image/sgi/pcl", "/image/sgi/pcx", "/image/sgi/pfa", "/image/sgi/pgm", 
                "/image/sgi/psb", "/image/sgi/ptif", "/image/sgi/p7", "/image/sgi/ras", "/image/sgi/sgi", "/image/sgi/sun", 
                "/image/sgi/tga", "/image/sgi/vda", "/image/sgi/vicar", "/image/sgi/viff", "/image/sgi/vips", "/image/sgi/xbm", 
                "/image/sgi/xpm", "/image/sgi/xv", "/image/sun", "/image/sun/jpg", "/image/sun/jpeg", "/image/sun/png", 
                "/image/sun/tiff", "/image/sun/webp", "/image/sun/gif", "/image/sun/bmp", "/image/sun/svg", "/image/sun/psd", 
                "/image/sun/ai", "/image/sun/eps", "/image/sun/svgz", "/image/sun/dcx", "/image/sun/dds", "/image/sun/dpx", 
                "/image/sun/exr", "/image/sun/fits", "/image/sun/jpc", "/image/sun/jpe", "/image/sun/jps", "/image/sun/jpm", 
                "/image/sun/jfif", "/image/sun/jng", "/image/sun/j2c", "/image/sun/j2k", "/image/sun/miff", "/image/sun/mng", 
                "/image/sun/palm", "/image/sun/pam", "/image/sun/pbm", "/image/sun/pcd", "/image/sun/pcds", "/image/sun/pcl", 
                "/image/sun/pcx", "/image/sun/pfa", "/image/sun/pgm", "/image/sun/psb", "/image/sun/ptif", "/image/sun/p7", 
                "/image/sun/ras", "/image/sun/sgi", "/image/sun/sun", "/image/sun/tga", "/image/sun/vda", "/image/sun/vicar", 
                "/image/sun/viff", "/image/sun/vips", "/image/sun/xbm", "/image/sun/xpm", "/image/sun/xv", "/image/vicar", 
                "/image/vicar/jpg", "/image/vicar/jpeg", "/image/vicar/png", "/image/vicar/tiff", "/image/vicar/webp", 
                "/image/vicar/gif", "/image/vicar/bmp", "/image/vicar/svg", "/image/vicar/psd", "/image/vicar/ai", 
                "/image/vicar/eps", "/image/vicar/svgz", "/image/vicar/dcx", "/image/vicar/dds", "/image/vicar/dpx", 
                "/image/vicar/exr", "/image/vicar/fits", "/image/vicar/jpc", "/image/vicar/jpe", "/image/vicar/jps", 
                "/image/vicar/jpm", "/image/vicar/jfif", "/image/vicar/jng", "/image/vicar/j2c", "/image/vicar/j2k", 
                "/image/vicar/miff", "/image/vicar/mng", "/image/vicar/palm", "/image/vicar/pam", "/image/vicar/pbm", 
                "/image/vicar/pcd", "/image/vicar/pcds", "/image/vicar/pcl", "/image/vicar/pcx", "/image/vicar/pfa", 
                "/image/vicar/pgm", "/image/vicar/psb", "/image/vicar/ptif", "/image/vicar/p7", "/image/vicar/ras", 
                "/image/vicar/sgi", "/image/vicar/sun", "/image/vicar/tga", "/image/vicar/vda", "/image/vicar/vicar", 
                "/image/vicar/viff", "/image/vicar/vips", "/image/vicar/xbm", "/image/vicar/xpm", "/image/vicar/xv", 
                "/image/viff", "/image/viff/jpg", "/image/viff/jpeg", "/image/viff/png", "/image/viff/tiff", "/image/viff/webp",
                "/image/viff/gif", "/image/viff/bmp", "/image/viff/svg", "/image/viff/psd", "/image/viff/ai", "/image/viff/eps", 
                "/image/viff/svgz", "/image/viff/dcx", "/image/viff/dds", "/image/viff/dpx", "/image/viff/exr", 
                "/image/viff/fits", "/image/viff/jpc", "/image/viff/jpe", "/image/viff/jps", "/image/viff/jpm", 
                "/image/viff/jfif", "/image/viff/jng", "/image/viff/j2c", "/image/viff/j2k", "/image/viff/miff", 
                "/image/viff/mng", "/image/viff/palm", "/image/viff/pam", "/image/viff/pbm", "/image/viff/pcd", 
                "/image/viff/pcds", "/image/viff/pcl", "/image/viff/pcx", "/image/viff/pfa", "/image/viff/pgm", 
                "/image/viff/psb", "/image/viff/ptif", "/image/viff/p7", "/image/viff/ras", "/image/viff/sgi", 
                "/image/viff/sun", "/image/viff/tga", "/image/viff/vda", "/image/viff/vicar", "/image/viff/viff", 
                "/image/viff/vips", "/image/viff/xbm", "/image/viff/xpm", "/image/viff/xv", "/image/vips", "/image/vips/jpg",
                 "/image/vips/jpeg", "/image/vips/png", "/image/vips/tiff", "/image/vips/webp", "/image/vips/gif", 
                 "/image/vips/bmp", "/image/vips/svg", "/image/vips/psd", "/image/vips/ai", "/image/vips/eps", 
                 "/image/vips/svgz", "/image/vips/dcx", "/image/vips/dds", "/image/vips/dpx", "/image/vips/exr", 
                 "/image/vips/fits", "/image/vips/jpc", "/image/vips/jpe", "/image/vips/jps", "/image/vips/jpm", 
                 "/image/vips/jfif", "/image/vips/jng", "/image/vips/j2c", "/image/vips/j2k", "/image/vips/miff", 
                 "/image/vips/mng", "/image/vips/palm", "/image/vips/pam", "/image/vips/pbm", "/image/vips/pcd", 
                 "/image/vips/pcds", "/image/vips/pcl", "/image/vips/pcx", "/image/vips/pfa", "/image/vips/pgm", 
                 "/image/vips/psb", "/image/vips/ptif", "/image/vips/p7", "/image/vips/ras", "/image/vips/sgi", 
                 "/image/vips/sun", "/image/vips/tga", "/image/vips/vda", "/image/vips/vicar", "/image/vips/viff", 
                 "/image/vips/vips", "/image/vips/xbm", "/image/vips/xpm", "/image/vips/xv", "/image/xbm",
                  "/image/xbm/jpg", "/image/xbm/jpeg", "/image/xbm/png", "/image/xbm/tiff", "/image/xbm/webp", 
                  "/image/xbm/gif", "/image/xbm/bmp", "/image/xbm/svg", "/image/xbm/psd", "/image/xbm/ai", 
                  "/image/xbm/eps", "/image/xbm/svgz", "/image/xbm/dcx", "/image/xbm/dds", "/image/xbm/dpx", 
                  "/image/xbm/exr", "/image/xbm/fits", "/image/xbm/jpc", "/image/xbm/jpe", "/image/xbm/jps", 
                  "/image/xbm/jpm", "/image/xbm/jfif", "/image/xbm/jng", "/image/xbm/j2c", "/image/xbm/j2k", 
                  "/image/xbm/miff", "/image/xbm/mng", "/image/xbm/palm", "/image/xbm/pam", "/image/xbm/pbm",
                   "/image/xbm/pcd", "/image/xbm/pcds", "/image/xbm/pcl", "/image/xbm/pcx", "/image/xbm/pfa", 
                   "/image/xbm/pgm", "/image/xbm/psb", "/image/xbm/ptif", "/image/xbm/p7", "/image/xbm/ras", 
                   "/image/xbm/sgi", "/image/xbm/sun", "/image/xbm/tga", "/image/xbm/vda", "/image/xbm/vicar", 
                   "/image/xbm/viff", "/image/xbm/vips", "/image/xbm/xbm", "/image/xbm/xpm", "/image/xbm/xv", 
                   "/image/xpm", "/image/xpm/jpg", "/image/xpm/jpeg", "/image/xpm/png", "/image/xpm/tiff", 
                   "/image/xpm/webp", "/image/xpm/gif", "/image/xpm/bmp", "/image/xpm/svg", "/image/xpm/psd", 
                   "/image/xpm/ai", "/image/xpm/eps", "/image/xpm/svgz", "/image/xpm/dcx", "/image/xpm/dds", 
                   "/image/xpm/dpx", "/image/xpm/exr", "/image/xpm/fits", "/image/xpm/jpc", "/image/xpm/jpe",
                    "/image/xpm/jps", "/image/xpm/jpm", "/image/xpm/jfif", "/image/xpm/jng", "/image/xpm/j2c",
                     "/image/xpm/j2k", "/image/xpm/miff", "/image/xpm/mng", "/image/xpm/palm", "/image/xpm/pam", 
                     "/image/xpm/pbm", "/image/xpm/pcd", "/image/xpm/pcds", "/image/xpm/pcl", "/image/xpm/pcx", 
                     "/image/xpm/pfa", "/image/xpm/pgm", "/image/xpm/psb", "/image/xpm/ptif", "/image/xpm/p7", 
                     "/image/xpm/ras", "/image/xpm/sgi", "/image/xpm/sun", "/image/xpm/tga", "/image/xpm/vda", 
                     "/image/xpm/vicar", "/image/xpm/viff", "/image/xpm/vips", "/image/xpm/xbm", "/image/xpm/xpm", 
                     "/image/xpm/xv", "/image/xv", "/image/xv/jpg", "/image/xv/jpeg", "/image/xv/png", "/image/xv/tiff",
                      "/image/xv/webp", "/image/xv/gif", "/image/xv/bmp", "/image/xv/svg", "/image/xv/psd", "/image/xv/ai", 
                      "/image/xv/eps", "/image/xv/svgz", "/image/xv/dcx", "/image/xv/dds", "/image/xv/dpx", "/image/xv/exr",
                       "/image/xv/fits", "/image/xv/jpc", "/image/xv/jpe", "/image/xv/jps", "/image/xv/jpm", "/image/xv/jfif",
                        "/image/xv/jng", "/image/xv/j2c", "/image/xv/j2k", "/image/xv/miff", "/image/xv/mng", "/image/xv/palm",
                    "/image/xv/pam", "/image/xv/pbm", "/image/xv/pcd", "/image/xv/pcds", "/image/xv/pcl", "/image/xv/pcx", 
                    "/image/xv/pfa", "/image/xv/pgm", "/image/xv/psb", "/image/xv/ptif", "/image/xv/p7", 
                    "/image/xv/ras", "/image/xv/sgi", "/image/xv/sun", "/image/xv/tga", "/image/xv/vda", 
                    "/image/xv/vicar", "/image/xv/viff", "/image/xv/vips", "/image/xv/xbm", "/image/xv/xpm", "/image/xv/xv"],
                  // You have to configure or you won't precompile
                  ignoreHTTPSErrors: true,
                
                  skipThirdPartyRequests: true,
                  renderer: new Renderer({
                      skipThirdPartyRequests: true,  
                      maxConcurrentRoutes: 2,
                      headless: true,
                      // In main.js, document.dispatchEvent(new Event('render-event')) should correspond to the event name of both.
                      renderAfterDocumentEvent: 'render-event'
                  })
              }),
          ],
      };
    }
}
